# Generated by Django 4.0 on 2022-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pass1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='pass2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='pnum',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
