# Generated by Django 4.0 on 2022-04-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_register_pass1_alter_register_pass2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Users',
        ),
    ]
