# Generated by Django 4.0 on 2022-04-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_register_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Register',
        ),
    ]
