# Generated by Django 4.0 on 2022-04-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_users_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gujrati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='food/images')),
            ],
        ),
    ]
