# Generated by Django 4.0 on 2022-04-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_gujrati'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gujrati',
            new_name='Product',
        ),
    ]
