# Generated by Django 4.0 on 2022-04-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rename_gujrati_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
