# Generated by Django 4.0 on 2022-04-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_rename_products_product_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
