# Generated by Django 4.0 on 2022-04-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_product_desc_product_img_product_name_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Gujproduct',
        ),
    ]
