# Generated by Django 4.0 on 2022-04-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_chinesseproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(null=True, upload_to='pics')),
                ('desc', models.TextField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Chinesseproduct',
        ),
        migrations.DeleteModel(
            name='Gujproduct',
        ),
        migrations.DeleteModel(
            name='Indianstreetproduct',
        ),
        migrations.DeleteModel(
            name='Punjabijproduct',
        ),
        migrations.DeleteModel(
            name='Rajsthaniproduct',
        ),
        migrations.DeleteModel(
            name='Southjproduct',
        ),
    ]
