# Generated by Django 4.0 on 2022-04-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_add_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_product',
        ),
    ]
