# Generated by Django 4.0 on 2022-04-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_delete_add_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
