# Generated by Django 4.0 on 2022-04-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lname',
        ),
    ]
