# Generated by Django 4.0 on 2022-04-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
