# Generated by Django 4.0 on 2022-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_delete_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
