# Generated by Django 4.0 on 2022-05-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0031_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaruant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('mail', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
